server:
  port: 8080

spring:
  application:
    name: order-api
  
  # PostgreSQL 配置
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update  # 开发环境用 update，生产环境用 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    
  # 数据库初始化
  sql:
    init:
      mode: always
      continue-on-error: false

# 日志配置
logging:
  level:
    com.example.demo.mapper: DEBUG

# MyBatis 配置
mybatis:
  # mapper XML文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类包路径
  type-aliases-package: com.wm.entity
  # 驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

auth:
  # token认证白名单
  whitelist:
    - /tenant/retrieve
    - /dish/retrieve
    - /category/retrieve
    - /table/retrieve
    - /order/retrieve
    - /order/update
    - /admin/user/login
    - /sse/connect