server:
  port: 8080

spring:
  profiles:
    active: prod

  application:
    name: order-api
  
  # PostgreSQL 配置
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: appadmin
    password: admin1234
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: redis1234
      database: 0

# MyBatis 配置
mybatis:
  # mapper XML文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类包路径
  type-aliases-package: com.wm.entity
  # 驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

#白名单
whitelist:
  whitelists:
    tenant: []
    auth:
      - /tenant/retrieve
      - /admin/user/login
      - /sse/connect
      - /file/image